# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e707155e91d5352f3f0288929b2bfc8c18bb7d19ebbb2de49591be34aaaf4d82b1a9964f87089c00c0f3a2c5be781825220969184f5f8f76add5f0e49d26e6bf

test:
  secret_key_base: 1cf757e69099a0b0e22f162d6612043db1f5d9dc8da4bd1bd28dd9e7da48f395ff242c767577bd1db910cb248553ae8c2b372faedc7df0584215175fb8386290

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
